# Generated by Django 5.2.3 on 2025-07-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_taskhistory_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='task_id_snapshot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
